"""
HU Voice AI API - Testing and Usage Examples

This script demonstrates how to use the HU Voice AI API
"""

import requests
import json
from typing import Dict, List, Optional
import time

# Configuration
BASE_URL = "http://localhost:5000"
CONVERSATION_ID = None  # Will be generated by API


class HUVoiceAIClient:
    """Client for HU Voice AI API"""
    
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.conversation_id = None
    
    def health_check(self) -> Dict:
        """Check API health"""
        try:
            response = requests.get(f"{self.base_url}/health", timeout=10)
            return response.json()
        except Exception as e:
            return {"status": "error", "error": str(e)}
    
    def get_status(self) -> Dict:
        """Get API status"""
        try:
            response = requests.get(f"{self.base_url}/status", timeout=10)
            return response.json()
        except Exception as e:
            return {"status": "error", "error": str(e)}
    
    def chat(
        self,
        message: str,
        conversation_id: Optional[str] = None
    ) -> Dict:
        """Send message and get response"""
        
        payload = {
            "message": message,
            "conversation_id": conversation_id or self.conversation_id
        }
        
        try:
            response = requests.post(
                f"{self.base_url}/chat",
                json=payload,
                timeout=30
            )
            
            # Try to parse JSON
            try:
                data = response.json()
            except Exception as json_error:
                # Handle non-JSON responses
                print(f"\n⚠ Warning: Non-JSON response received (Status: {response.status_code})")
                print(f"Response content: {response.text[:200]}")
                
                # Return error dict if response is HTML or empty
                if response.status_code != 200:
                    return {
                        "success": False,
                        "error": f"HTTP {response.status_code}",
                        "details": response.text[:100],
                        "conversation_id": conversation_id or self.conversation_id
                    }
                else:
                    return {
                        "success": False,
                        "error": "Invalid JSON response",
                        "details": str(json_error),
                        "conversation_id": conversation_id or self.conversation_id
                    }
            
            # Store conversation ID for future messages
            if "conversation_id" in data:
                self.conversation_id = data["conversation_id"]
            
            return data
        
        except requests.exceptions.Timeout:
            return {
                "success": False,
                "error": "Request timeout",
                "conversation_id": conversation_id or self.conversation_id
            }
        
        except requests.exceptions.ConnectionError:
            return {
                "success": False,
                "error": "Connection error - API may be down",
                "conversation_id": conversation_id or self.conversation_id
            }
        
        except Exception as e:
            return {
                "success": False,
                "error": f"Unexpected error: {str(e)}",
                "conversation_id": conversation_id or self.conversation_id
            }
    
    def get_conversation_history(
        self,
        conversation_id: Optional[str] = None
    ) -> Dict:
        """Get conversation history"""
        
        conv_id = conversation_id or self.conversation_id
        
        try:
            response = requests.get(
                f"{self.base_url}/conversations/{conv_id}",
                timeout=10
            )
            return response.json()
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def clear_conversation(
        self,
        conversation_id: Optional[str] = None
    ) -> Dict:
        """Clear conversation history"""
        
        conv_id = conversation_id or self.conversation_id
        
        try:
            response = requests.delete(
                f"{self.base_url}/conversations/{conv_id}",
                timeout=10
            )
            return response.json()
        except Exception as e:
            return {"success": False, "error": str(e)}


def print_response(title: str, data: Dict):
    """Pretty print response"""
    print("\n" + "="*60)
    print(f"  {title}")
    print("="*60)
    print(json.dumps(data, indent=2, ensure_ascii=False))


def test_english_conversation():
    """Test English conversation"""
    print("\n\n" + "#"*60)
    print("# TEST 1: English Conversation")
    print("#"*60)
    
    client = HUVoiceAIClient()
    
    # Message 1
    response = client.chat("What are the placement statistics of the university?")
    print_response("Message 1: Placement Statistics", response)
    
    # Message 2 (Follow-up)
    response = client.chat("What are the top companies recruiting?")
    print_response("Message 2: Top Companies", response)
    
    # Message 3 (Another follow-up)
    response = client.chat("Tell me about the average salary package")
    print_response("Message 3: Salary Package", response)
    
    return client.conversation_id


def test_hindi_conversation():
    """Test Hindi conversation"""
    print("\n\n" + "#"*60)
    print("# TEST 2: Hindi Conversation")
    print("#"*60)
    
    client = HUVoiceAIClient()
    
    # Message 1
    response = client.chat("प्रवेश के लिए क्या योग्यता चाहिए?")
    print_response("Message 1: प्रवेश योग्यता", response)
    
    # Message 2
    response = client.chat("छात्रवृत्ति के बारे में बताइये")
    print_response("Message 2: छात्रवृत्ति", response)


def test_hinglish_conversation():
    """Test Hinglish conversation"""
    print("\n\n" + "#"*60)
    print("# TEST 3: Hinglish Conversation")
    print("#"*60)
    
    client = HUVoiceAIClient()
    
    # Message 1
    response = client.chat("campus facilities kaise hain?")
    print_response("Message 1: Campus Facilities", response)
    
    # Message 2
    response = client.chat("hostel accommodation ki kya arrangement hai?")
    print_response("Message 2: Hostel Accommodation", response)


def test_current_affairs():
    """Test current affairs/news query"""
    print("\n\n" + "#"*60)
    print("# TEST 4: Current Affairs Query")
    print("#"*60)
    
    client = HUVoiceAIClient()
    
    response = client.chat("What are the latest developments in AI technology in 2025?")
    print_response("Latest AI Developments", response)


def test_health_endpoints():
    """Test health check endpoints"""
    print("\n\n" + "#"*60)
    print("# TEST 5: Health Check Endpoints")
    print("#"*60)
    
    client = HUVoiceAIClient()
    
    # Health check
    health = client.health_check()
    print_response("Health Check", health)
    
    # Status
    status = client.get_status()
    print_response("API Status", status)


def test_conversation_history():
    """Test conversation history retrieval"""
    print("\n\n" + "#"*60)
    print("# TEST 6: Conversation History")
    print("#"*60)
    
    client = HUVoiceAIClient()
    
    # Send multiple messages
    print("Sending multiple messages...")
    client.chat("Hello, how are you?")
    time.sleep(1)
    client.chat("Tell me about your features")
    time.sleep(1)
    client.chat("Can you help with studies?")
    
    # Get history
    history = client.get_conversation_history()
    print_response("Conversation History", history)
    
    return client.conversation_id


def test_multiple_conversations():
    """Test multiple independent conversations"""
    print("\n\n" + "#"*60)
    print("# TEST 7: Multiple Conversations")
    print("#"*60)
    
    # Conversation 1
    client1 = HUVoiceAIClient()
    print("Creating Conversation 1...")
    response1 = client1.chat("What is your name?")
    print_response("Conversation 1", response1)
    
    # Conversation 2
    client2 = HUVoiceAIClient()
    print("\nCreating Conversation 2...")
    response2 = client2.chat("Mujhe admissions ke bare mein bataao")
    print_response("Conversation 2", response2)
    
    print(f"\nConversation 1 ID: {client1.conversation_id}")
    print(f"Conversation 2 ID: {client2.conversation_id}")


def test_university_knowledge():
    """Test university knowledge base queries"""
    print("\n\n" + "#"*60)
    print("# TEST 8: University Knowledge Base")
    print("#"*60)
    
    client = HUVoiceAIClient()
    
    queries = [
        "Tell me about fees structure",
        "What courses are available?",
        "Faculty information please",
        "Tell me about campus facilities"
    ]
    
    for i, query in enumerate(queries, 1):
        response = client.chat(query)
        print_response(f"Query {i}: {query}", response)
        time.sleep(1)


def test_error_handling():
    """Test error handling"""
    print("\n\n" + "#"*60)
    print("# TEST 9: Error Handling")
    print("#"*60)
    
    # Test with empty message
    print("\n1. Testing with empty message:")
    try:
        response = requests.post(
            f"{BASE_URL}/chat",
            json={"message": "", "conversation_id": "test"}
        )
        print_response("Empty Message Response", response.json())
    except Exception as e:
        print(f"Error: {e}")
    
    # Test non-existent conversation
    print("\n2. Testing non-existent conversation:")
    try:
        response = requests.get(
            f"{BASE_URL}/conversations/non_existent_conv_id"
        )
        print_response("Non-existent Conversation", response.json())
    except Exception as e:
        print(f"Error: {e}")


def main():
    """Run all tests"""
    print("\n\n")
    print("╔" + "="*58 + "╗")
    print("║" + " "*10 + "HU Voice AI API - Testing Suite" + " "*16 + "║")
    print("╚" + "="*58 + "╝")
    
    try:
        # Check API is running
        print("\nChecking if API is running...")
        client = HUVoiceAIClient()
        health = client.health_check()
        
        if health.get("status") == "healthy":
            print("✓ API is running and healthy!")
        else:
            print("✗ API is not responding properly")
            return
        
        # Run tests
        test_health_endpoints()
        test_english_conversation()
        test_hindi_conversation()
        test_hinglish_conversation()
        test_current_affairs()
        test_conversation_history()
        test_multiple_conversations()
        test_university_knowledge()
        test_error_handling()
        
        print("\n\n" + "="*60)
        print("  All tests completed!")
        print("="*60)
        print("\nNext steps:")
        print("1. Check the responses for quality and accuracy")
        print("2. Review logs in app.log for any errors")
        print("3. Test with custom messages")
        print("4. Check API documentation at http://localhost:5000/docs")
        print("\n")
    
    except requests.exceptions.ConnectionError:
        print("\n✗ Cannot connect to API!")
        print(f"Please make sure the API is running at {BASE_URL}")
        print("\nStart the API with:")
        print("  Windows: start.bat")
        print("  Linux/Mac: bash start.sh")
    
    except Exception as e:
        print(f"\n✗ Error during testing: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
